name: ar_zabbix

services:

  zabbix_server:

    image: zabbix/zabbix-server-pgsql:7.4.10-alpine
    restart: unless-stopped
    user:

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    cap_add:
      -

    tmpfs:
      - /tmp

    environment:

      DB_SERVER_HOST: zabbix_postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

    volumes:

      - ./server_data/alertscripts:/usr/lib/zabbix/alertscripts
      - ./server_data/externalscripts:/usr/lib/zabbix/externalscripts
      - ./server_data/modules:/var/lib/zabbix/modules
      - ./server_data/enc:/var/lib/zabbix/enc
      - ./server_data/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./server_data/ssl/certs:/var/lib/zabbix/ssl/certs
      - ./server_data/ssl/keys:/var/lib/zabbix/ssl/keys
      - ./server_data/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - ./server_data/snmptraps:/var/lib/zabbix/snmptraps
      - ./server_data/mibs:/var/lib/zabbix/mibs
      - ./server_data/export:/var/lib/zabbix/export 

    healthcheck:

    cpus:

    mem_limit:

    pids_limit:


    networks:
      - backend

  zabbix_frontend:

    image: zabbix/zabbix-web-nginx-pgsql:7.4.10-alpine
    restart: unless-stopped
    user:

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    cap_add:
      -

    tmpfs:
      - /tmp

    environment:

      DB_SERVER_HOST: zabbix_postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix_server

    ports: 
      - "8080:8080"

    volumes:

      - ./frontend_data/nginx:/etc/ssl/nginx
      - ./frontend_data/certs:/etc/zabbix/web/certs
      - ./frontend_data/enc:/var/lib/zabbix/enc

    healthcheck:

    cpus:

    mem_limit:

    pids_limit:

    networks:
      - backend

  zabbix_agent:

    image: zabbix/zabbix-agent:7.4.10-alpine
    restart: unless-stopped
    user:

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    cap_add:
      -

    tmpfs:
      - /tmp

    environment:

      ZBX_SERVER_HOST: zabbix_server
      ZBX_PASSIVE_ALLOW: true
      ZBX_HOSTNAME: zabbix_agent

    volumes:

    healthcheck:

    cpus:

    mem_limit:

    pids_limit:

    networks:
      - backend

  zabbix_database:

    image: timescale/timescaledb:2.27.1-pg18
    restart: unless-stopped
    user: 999:999

    # dont forget:  CREATE EXTENSION IF NOT EXISTS timescaledb;

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    cap_add:
      -

    tmpfs:
      - /tmp

    environment:

      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

    volumes:
      - ./postgres_data:/var/lib/postgresql    

    healthcheck:

    cpus:

    mem_limit:

    pids_limit:

    shm_size:

    networks:
      - backend

  zabbix_grafana:

    image: grafana/grafana:13.0.1-security-01-ubuntu
    restart: unless-stopped
    user:

    read_only: true

    security_opt:
      - no-new-privileges

    cap_drop:
      - ALL

    cap_add:
      -

    tmpfs:
      - /tmp

    environment:

    volumes:

    healthcheck:

    cpus:

    mem_limit:

    pids_limit:

    networks:
      - backend


networks:

  frontend:

  backend:
    internal: true


volumes:

  postgres_data:

  alertscripts:
  externalscripts:
  modules:
  enc:
  ssh_keys:
  certs:
  keys:
  ssl_ca:
  snmptraps:
  mibs:
  export:

  nginx:
  web_certs:
  web_enc:
  
